server:
  port: 8181
spring:
  thymeleaf:
    # 此处配置如果是 /templates/ 在controller中 返回页面时 只能是 xx/yy 不可以为 /xx/yy
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
